/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ApiPublicAutomationTickRouteImport } from './routes/api/public/automation-tick'
import { Route as AuthenticatedClientUploadsRouteImport } from './routes/_authenticated/client/uploads'
import { Route as AuthenticatedClientTasksRouteImport } from './routes/_authenticated/client/tasks'
import { Route as AuthenticatedClientRoadmapRouteImport } from './routes/_authenticated/client/roadmap'
import { Route as AuthenticatedClientReportsRouteImport } from './routes/_authenticated/client/reports'
import { Route as AuthenticatedClientMessagesRouteImport } from './routes/_authenticated/client/messages'
import { Route as AuthenticatedClientChannelsRouteImport } from './routes/_authenticated/client/channels'
import { Route as AuthenticatedClientCalendarRouteImport } from './routes/_authenticated/client/calendar'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTrashRouteImport } from './routes/_authenticated/admin/trash'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSearchRouteImport } from './routes/_authenticated/admin/search'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminReachRouteImport } from './routes/_authenticated/admin/reach'
import { Route as AuthenticatedAdminQueueRouteImport } from './routes/_authenticated/admin/queue'
import { Route as AuthenticatedAdminPostizRouteImport } from './routes/_authenticated/admin/postiz'
import { Route as AuthenticatedAdminPlannerRouteImport } from './routes/_authenticated/admin/planner'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminEngagementRouteImport } from './routes/_authenticated/admin/engagement'
import { Route as AuthenticatedAdminEditorRouteImport } from './routes/_authenticated/admin/editor'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCreateRouteImport } from './routes/_authenticated/admin/create'
import { Route as AuthenticatedAdminComposeRouteImport } from './routes/_authenticated/admin/compose'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminBulkRouteImport } from './routes/_authenticated/admin/bulk'
import { Route as AuthenticatedAdminBesttimeRouteImport } from './routes/_authenticated/admin/besttime'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin/clients.index'
import { Route as ApiPublicV1PostsRouteImport } from './routes/api/public/v1/posts'
import { Route as ApiPublicV1ClientsRouteImport } from './routes/api/public/v1/clients'
import { Route as ApiPublicHooksPostizProvisionRetryRouteImport } from './routes/api/public/hooks/postiz-provision-retry'
import { Route as AuthenticatedClientChannelsCallbackRouteImport } from './routes/_authenticated/client/channels.callback'
import { Route as AuthenticatedAdminClientsNewRouteImport } from './routes/_authenticated/admin/clients.new'
import { Route as AuthenticatedAdminClientsIntakeRouteImport } from './routes/_authenticated/admin/clients.intake'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'
import { Route as AuthenticatedAdminClientsIdEditRouteImport } from './routes/_authenticated/admin/clients.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicAutomationTickRoute = ApiPublicAutomationTickRouteImport.update({
  id: '/api/public/automation-tick',
  path: '/api/public/automation-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientUploadsRoute =
  AuthenticatedClientUploadsRouteImport.update({
    id: '/client/uploads',
    path: '/client/uploads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientTasksRoute =
  AuthenticatedClientTasksRouteImport.update({
    id: '/client/tasks',
    path: '/client/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientRoadmapRoute =
  AuthenticatedClientRoadmapRouteImport.update({
    id: '/client/roadmap',
    path: '/client/roadmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientReportsRoute =
  AuthenticatedClientReportsRouteImport.update({
    id: '/client/reports',
    path: '/client/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientMessagesRoute =
  AuthenticatedClientMessagesRouteImport.update({
    id: '/client/messages',
    path: '/client/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientChannelsRoute =
  AuthenticatedClientChannelsRouteImport.update({
    id: '/client/channels',
    path: '/client/channels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientCalendarRoute =
  AuthenticatedClientCalendarRouteImport.update({
    id: '/client/calendar',
    path: '/client/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTrashRoute = AuthenticatedAdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSearchRoute =
  AuthenticatedAdminSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReachRoute = AuthenticatedAdminReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminQueueRoute = AuthenticatedAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPostizRoute =
  AuthenticatedAdminPostizRouteImport.update({
    id: '/postiz',
    path: '/postiz',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlannerRoute =
  AuthenticatedAdminPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEngagementRoute =
  AuthenticatedAdminEngagementRouteImport.update({
    id: '/engagement',
    path: '/engagement',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEditorRoute =
  AuthenticatedAdminEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreateRoute =
  AuthenticatedAdminCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComposeRoute =
  AuthenticatedAdminComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBulkRoute = AuthenticatedAdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBesttimeRoute =
  AuthenticatedAdminBesttimeRouteImport.update({
    id: '/besttime',
    path: '/besttime',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicV1PostsRoute = ApiPublicV1PostsRouteImport.update({
  id: '/api/public/v1/posts',
  path: '/api/public/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClientsRoute = ApiPublicV1ClientsRouteImport.update({
  id: '/api/public/v1/clients',
  path: '/api/public/v1/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPostizProvisionRetryRoute =
  ApiPublicHooksPostizProvisionRetryRouteImport.update({
    id: '/api/public/hooks/postiz-provision-retry',
    path: '/api/public/hooks/postiz-provision-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientChannelsCallbackRoute =
  AuthenticatedClientChannelsCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedClientChannelsRoute,
  } as any)
const AuthenticatedAdminClientsNewRoute =
  AuthenticatedAdminClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIntakeRoute =
  AuthenticatedAdminClientsIntakeRouteImport.update({
    id: '/clients/intake',
    path: '/clients/intake',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdEditRoute =
  AuthenticatedAdminClientsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/besttime': typeof AuthenticatedAdminBesttimeRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/compose': typeof AuthenticatedAdminComposeRoute
  '/admin/create': typeof AuthenticatedAdminCreateRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/editor': typeof AuthenticatedAdminEditorRoute
  '/admin/engagement': typeof AuthenticatedAdminEngagementRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/admin/postiz': typeof AuthenticatedAdminPostizRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/reach': typeof AuthenticatedAdminReachRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/client/channels': typeof AuthenticatedClientChannelsRouteWithChildren
  '/client/messages': typeof AuthenticatedClientMessagesRoute
  '/client/reports': typeof AuthenticatedClientReportsRoute
  '/client/roadmap': typeof AuthenticatedClientRoadmapRoute
  '/client/tasks': typeof AuthenticatedClientTasksRoute
  '/client/uploads': typeof AuthenticatedClientUploadsRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/intake': typeof AuthenticatedAdminClientsIntakeRoute
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/client/channels/callback': typeof AuthenticatedClientChannelsCallbackRoute
  '/api/public/hooks/postiz-provision-retry': typeof ApiPublicHooksPostizProvisionRetryRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/besttime': typeof AuthenticatedAdminBesttimeRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/compose': typeof AuthenticatedAdminComposeRoute
  '/admin/create': typeof AuthenticatedAdminCreateRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/editor': typeof AuthenticatedAdminEditorRoute
  '/admin/engagement': typeof AuthenticatedAdminEngagementRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/admin/postiz': typeof AuthenticatedAdminPostizRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/reach': typeof AuthenticatedAdminReachRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/client/channels': typeof AuthenticatedClientChannelsRouteWithChildren
  '/client/messages': typeof AuthenticatedClientMessagesRoute
  '/client/reports': typeof AuthenticatedClientReportsRoute
  '/client/roadmap': typeof AuthenticatedClientRoadmapRoute
  '/client/tasks': typeof AuthenticatedClientTasksRoute
  '/client/uploads': typeof AuthenticatedClientUploadsRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/intake': typeof AuthenticatedAdminClientsIntakeRoute
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/client/channels/callback': typeof AuthenticatedClientChannelsCallbackRoute
  '/api/public/hooks/postiz-provision-retry': typeof ApiPublicHooksPostizProvisionRetryRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/besttime': typeof AuthenticatedAdminBesttimeRoute
  '/_authenticated/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/compose': typeof AuthenticatedAdminComposeRoute
  '/_authenticated/admin/create': typeof AuthenticatedAdminCreateRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/editor': typeof AuthenticatedAdminEditorRoute
  '/_authenticated/admin/engagement': typeof AuthenticatedAdminEngagementRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/_authenticated/admin/postiz': typeof AuthenticatedAdminPostizRoute
  '/_authenticated/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/_authenticated/admin/reach': typeof AuthenticatedAdminReachRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/search': typeof AuthenticatedAdminSearchRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/_authenticated/client/channels': typeof AuthenticatedClientChannelsRouteWithChildren
  '/_authenticated/client/messages': typeof AuthenticatedClientMessagesRoute
  '/_authenticated/client/reports': typeof AuthenticatedClientReportsRoute
  '/_authenticated/client/roadmap': typeof AuthenticatedClientRoadmapRoute
  '/_authenticated/client/tasks': typeof AuthenticatedClientTasksRoute
  '/_authenticated/client/uploads': typeof AuthenticatedClientUploadsRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/_authenticated/admin/clients/intake': typeof AuthenticatedAdminClientsIntakeRoute
  '/_authenticated/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/_authenticated/client/channels/callback': typeof AuthenticatedClientChannelsCallbackRoute
  '/api/public/hooks/postiz-provision-retry': typeof ApiPublicHooksPostizProvisionRetryRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/approvals'
    | '/admin/automations'
    | '/admin/besttime'
    | '/admin/bulk'
    | '/admin/campaigns'
    | '/admin/compose'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/editor'
    | '/admin/engagement'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/planner'
    | '/admin/postiz'
    | '/admin/queue'
    | '/admin/reach'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/team'
    | '/admin/trash'
    | '/admin/users'
    | '/admin/webhooks'
    | '/client/calendar'
    | '/client/channels'
    | '/client/messages'
    | '/client/reports'
    | '/client/roadmap'
    | '/client/tasks'
    | '/client/uploads'
    | '/api/public/automation-tick'
    | '/admin/clients/$id'
    | '/admin/clients/intake'
    | '/admin/clients/new'
    | '/client/channels/callback'
    | '/api/public/hooks/postiz-provision-retry'
    | '/api/public/v1/clients'
    | '/api/public/v1/posts'
    | '/admin/clients/'
    | '/admin/clients/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/approvals'
    | '/admin/automations'
    | '/admin/besttime'
    | '/admin/bulk'
    | '/admin/campaigns'
    | '/admin/compose'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/editor'
    | '/admin/engagement'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/planner'
    | '/admin/postiz'
    | '/admin/queue'
    | '/admin/reach'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/team'
    | '/admin/trash'
    | '/admin/users'
    | '/admin/webhooks'
    | '/client/calendar'
    | '/client/channels'
    | '/client/messages'
    | '/client/reports'
    | '/client/roadmap'
    | '/client/tasks'
    | '/client/uploads'
    | '/api/public/automation-tick'
    | '/admin/clients/$id'
    | '/admin/clients/intake'
    | '/admin/clients/new'
    | '/client/channels/callback'
    | '/api/public/hooks/postiz-provision-retry'
    | '/api/public/v1/clients'
    | '/api/public/v1/posts'
    | '/admin/clients'
    | '/admin/clients/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/besttime'
    | '/_authenticated/admin/bulk'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/compose'
    | '/_authenticated/admin/create'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/editor'
    | '/_authenticated/admin/engagement'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/planner'
    | '/_authenticated/admin/postiz'
    | '/_authenticated/admin/queue'
    | '/_authenticated/admin/reach'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/search'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/trash'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/client/calendar'
    | '/_authenticated/client/channels'
    | '/_authenticated/client/messages'
    | '/_authenticated/client/reports'
    | '/_authenticated/client/roadmap'
    | '/_authenticated/client/tasks'
    | '/_authenticated/client/uploads'
    | '/api/public/automation-tick'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/clients/intake'
    | '/_authenticated/admin/clients/new'
    | '/_authenticated/client/channels/callback'
    | '/api/public/hooks/postiz-provision-retry'
    | '/api/public/v1/clients'
    | '/api/public/v1/posts'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/clients/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAutomationTickRoute: typeof ApiPublicAutomationTickRoute
  ApiPublicHooksPostizProvisionRetryRoute: typeof ApiPublicHooksPostizProvisionRetryRoute
  ApiPublicV1ClientsRoute: typeof ApiPublicV1ClientsRoute
  ApiPublicV1PostsRoute: typeof ApiPublicV1PostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/automation-tick': {
      id: '/api/public/automation-tick'
      path: '/api/public/automation-tick'
      fullPath: '/api/public/automation-tick'
      preLoaderRoute: typeof ApiPublicAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/client/uploads': {
      id: '/_authenticated/client/uploads'
      path: '/client/uploads'
      fullPath: '/client/uploads'
      preLoaderRoute: typeof AuthenticatedClientUploadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/tasks': {
      id: '/_authenticated/client/tasks'
      path: '/client/tasks'
      fullPath: '/client/tasks'
      preLoaderRoute: typeof AuthenticatedClientTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/roadmap': {
      id: '/_authenticated/client/roadmap'
      path: '/client/roadmap'
      fullPath: '/client/roadmap'
      preLoaderRoute: typeof AuthenticatedClientRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/reports': {
      id: '/_authenticated/client/reports'
      path: '/client/reports'
      fullPath: '/client/reports'
      preLoaderRoute: typeof AuthenticatedClientReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/messages': {
      id: '/_authenticated/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof AuthenticatedClientMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/channels': {
      id: '/_authenticated/client/channels'
      path: '/client/channels'
      fullPath: '/client/channels'
      preLoaderRoute: typeof AuthenticatedClientChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/calendar': {
      id: '/_authenticated/client/calendar'
      path: '/client/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof AuthenticatedClientCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trash': {
      id: '/_authenticated/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AuthenticatedAdminTrashRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/search': {
      id: '/_authenticated/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AuthenticatedAdminSearchRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reach': {
      id: '/_authenticated/admin/reach'
      path: '/reach'
      fullPath: '/admin/reach'
      preLoaderRoute: typeof AuthenticatedAdminReachRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/queue': {
      id: '/_authenticated/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AuthenticatedAdminQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/postiz': {
      id: '/_authenticated/admin/postiz'
      path: '/postiz'
      fullPath: '/admin/postiz'
      preLoaderRoute: typeof AuthenticatedAdminPostizRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planner': {
      id: '/_authenticated/admin/planner'
      path: '/planner'
      fullPath: '/admin/planner'
      preLoaderRoute: typeof AuthenticatedAdminPlannerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/engagement': {
      id: '/_authenticated/admin/engagement'
      path: '/engagement'
      fullPath: '/admin/engagement'
      preLoaderRoute: typeof AuthenticatedAdminEngagementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/editor': {
      id: '/_authenticated/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AuthenticatedAdminEditorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/create': {
      id: '/_authenticated/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AuthenticatedAdminCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/compose': {
      id: '/_authenticated/admin/compose'
      path: '/compose'
      fullPath: '/admin/compose'
      preLoaderRoute: typeof AuthenticatedAdminComposeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bulk': {
      id: '/_authenticated/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AuthenticatedAdminBulkRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/besttime': {
      id: '/_authenticated/admin/besttime'
      path: '/besttime'
      fullPath: '/admin/besttime'
      preLoaderRoute: typeof AuthenticatedAdminBesttimeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/v1/posts': {
      id: '/api/public/v1/posts'
      path: '/api/public/v1/posts'
      fullPath: '/api/public/v1/posts'
      preLoaderRoute: typeof ApiPublicV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clients': {
      id: '/api/public/v1/clients'
      path: '/api/public/v1/clients'
      fullPath: '/api/public/v1/clients'
      preLoaderRoute: typeof ApiPublicV1ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/postiz-provision-retry': {
      id: '/api/public/hooks/postiz-provision-retry'
      path: '/api/public/hooks/postiz-provision-retry'
      fullPath: '/api/public/hooks/postiz-provision-retry'
      preLoaderRoute: typeof ApiPublicHooksPostizProvisionRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/client/channels/callback': {
      id: '/_authenticated/client/channels/callback'
      path: '/callback'
      fullPath: '/client/channels/callback'
      preLoaderRoute: typeof AuthenticatedClientChannelsCallbackRouteImport
      parentRoute: typeof AuthenticatedClientChannelsRoute
    }
    '/_authenticated/admin/clients/new': {
      id: '/_authenticated/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AuthenticatedAdminClientsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/intake': {
      id: '/_authenticated/admin/clients/intake'
      path: '/clients/intake'
      fullPath: '/admin/clients/intake'
      preLoaderRoute: typeof AuthenticatedAdminClientsIntakeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id/edit': {
      id: '/_authenticated/admin/clients/$id/edit'
      path: '/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminClientsIdRoute
    }
  }
}

interface AuthenticatedAdminClientsIdRouteChildren {
  AuthenticatedAdminClientsIdEditRoute: typeof AuthenticatedAdminClientsIdEditRoute
}

const AuthenticatedAdminClientsIdRouteChildren: AuthenticatedAdminClientsIdRouteChildren =
  {
    AuthenticatedAdminClientsIdEditRoute: AuthenticatedAdminClientsIdEditRoute,
  }

const AuthenticatedAdminClientsIdRouteWithChildren =
  AuthenticatedAdminClientsIdRoute._addFileChildren(
    AuthenticatedAdminClientsIdRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminBesttimeRoute: typeof AuthenticatedAdminBesttimeRoute
  AuthenticatedAdminBulkRoute: typeof AuthenticatedAdminBulkRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminComposeRoute: typeof AuthenticatedAdminComposeRoute
  AuthenticatedAdminCreateRoute: typeof AuthenticatedAdminCreateRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEditorRoute: typeof AuthenticatedAdminEditorRoute
  AuthenticatedAdminEngagementRoute: typeof AuthenticatedAdminEngagementRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPlannerRoute: typeof AuthenticatedAdminPlannerRoute
  AuthenticatedAdminPostizRoute: typeof AuthenticatedAdminPostizRoute
  AuthenticatedAdminQueueRoute: typeof AuthenticatedAdminQueueRoute
  AuthenticatedAdminReachRoute: typeof AuthenticatedAdminReachRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSearchRoute: typeof AuthenticatedAdminSearchRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTrashRoute: typeof AuthenticatedAdminTrashRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRouteWithChildren
  AuthenticatedAdminClientsIntakeRoute: typeof AuthenticatedAdminClientsIntakeRoute
  AuthenticatedAdminClientsNewRoute: typeof AuthenticatedAdminClientsNewRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
    AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
    AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
    AuthenticatedAdminBesttimeRoute: AuthenticatedAdminBesttimeRoute,
    AuthenticatedAdminBulkRoute: AuthenticatedAdminBulkRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminComposeRoute: AuthenticatedAdminComposeRoute,
    AuthenticatedAdminCreateRoute: AuthenticatedAdminCreateRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEditorRoute: AuthenticatedAdminEditorRoute,
    AuthenticatedAdminEngagementRoute: AuthenticatedAdminEngagementRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminPlannerRoute: AuthenticatedAdminPlannerRoute,
    AuthenticatedAdminPostizRoute: AuthenticatedAdminPostizRoute,
    AuthenticatedAdminQueueRoute: AuthenticatedAdminQueueRoute,
    AuthenticatedAdminReachRoute: AuthenticatedAdminReachRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSearchRoute: AuthenticatedAdminSearchRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTrashRoute: AuthenticatedAdminTrashRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
    AuthenticatedAdminClientsIdRoute:
      AuthenticatedAdminClientsIdRouteWithChildren,
    AuthenticatedAdminClientsIntakeRoute: AuthenticatedAdminClientsIntakeRoute,
    AuthenticatedAdminClientsNewRoute: AuthenticatedAdminClientsNewRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClientChannelsRouteChildren {
  AuthenticatedClientChannelsCallbackRoute: typeof AuthenticatedClientChannelsCallbackRoute
}

const AuthenticatedClientChannelsRouteChildren: AuthenticatedClientChannelsRouteChildren =
  {
    AuthenticatedClientChannelsCallbackRoute:
      AuthenticatedClientChannelsCallbackRoute,
  }

const AuthenticatedClientChannelsRouteWithChildren =
  AuthenticatedClientChannelsRoute._addFileChildren(
    AuthenticatedClientChannelsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientCalendarRoute: typeof AuthenticatedClientCalendarRoute
  AuthenticatedClientChannelsRoute: typeof AuthenticatedClientChannelsRouteWithChildren
  AuthenticatedClientMessagesRoute: typeof AuthenticatedClientMessagesRoute
  AuthenticatedClientReportsRoute: typeof AuthenticatedClientReportsRoute
  AuthenticatedClientRoadmapRoute: typeof AuthenticatedClientRoadmapRoute
  AuthenticatedClientTasksRoute: typeof AuthenticatedClientTasksRoute
  AuthenticatedClientUploadsRoute: typeof AuthenticatedClientUploadsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientCalendarRoute: AuthenticatedClientCalendarRoute,
  AuthenticatedClientChannelsRoute:
    AuthenticatedClientChannelsRouteWithChildren,
  AuthenticatedClientMessagesRoute: AuthenticatedClientMessagesRoute,
  AuthenticatedClientReportsRoute: AuthenticatedClientReportsRoute,
  AuthenticatedClientRoadmapRoute: AuthenticatedClientRoadmapRoute,
  AuthenticatedClientTasksRoute: AuthenticatedClientTasksRoute,
  AuthenticatedClientUploadsRoute: AuthenticatedClientUploadsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAutomationTickRoute: ApiPublicAutomationTickRoute,
  ApiPublicHooksPostizProvisionRetryRoute:
    ApiPublicHooksPostizProvisionRetryRoute,
  ApiPublicV1ClientsRoute: ApiPublicV1ClientsRoute,
  ApiPublicV1PostsRoute: ApiPublicV1PostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
